name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tag-and-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.1.0
      - name: Use Node version defined in '.nvmrc'
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: .nvmrc
      - name: Install Bit Version Manager 
        run: npm i -g @teambit/bvm
      - name: Install latest Bit version 
        run: bvm install
      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH
      - name: Set up bit config
        run: |
            bit config set analytics_reporting false
            bit config set anonymous_reporting false
            bit config set user.token $BIT_TOKEN
      - name: Install packages using bit
        run: bit install
      - name: Compile bit app and components
        run: bit compile
      - name: Build app and components
        run: bit build
      - name: Hard-tag pending components and app
        if: "github.event_name == 'push'"
        run: bit tag --persist
      - name: Tag bit app demo-app/devops-console-demo (in case of no soft tag)
        if: "github.event_name == 'push'"
        run: bit tag demo-app/devops-console-demo
      - name: Export components and app
        if: "github.event_name == 'push'"
        run: bit export --log trace
      - name: check for changes
        if: "github.event_name == 'push'"
        run: |
          if git diff --quiet --exit-code -- .bitmap; then
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Commit changes made to .bitmap
        if: "github.event_name == 'push' && env.changes_exist == 'true'"
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add .bitmap
          git commit -m "update .bitmap with new component versions (automated). --skip-ci"
          git push
